name: run-tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.1]
        laravel: [9.*]
        dependency-version: [prefer-stable]
        include:
          -   laravel: 9.*
              testbench: 7.*
        exclude:
          # excludes prefer-lowest 5.8 test on php 7.4
          -   laravel: 5.8
              php: 7.4
              dependency-version: prefer-lowest
          -   laravel: 5.8
              php: 8.0
              dependency-version: prefer-stable
          -   laravel: 5.8
              php: 8.0
              dependency-version: prefer-lowest
          -   laravel: 6.*
              php: 8.0
              dependency-version: prefer-lowest
          -   laravel: 7.*
              php: 8.0
              dependency-version: prefer-lowest
          -   laravel: 8.*
              php: 8.0
              dependency-version: prefer-lowest
          -   laravel: 8.*
              php: 7.2
          -   laravel: 9.*
              php: 7.2
          -   laravel: 9.*
              php: 7.3
          -   laravel: 9.*
              php: 7.4

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      -   name: Checkout code
          uses: actions/checkout@v1

      -   name: Cache dependencies
          uses: actions/cache@v1
          with:
            path: ~/.composer/cache/files
            key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
            coverage: none

      -   name: Install dependencies
          run: |
            composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
            composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
      -   name: Execute tests
          run: vendor/bin/pest